// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Thu Sep 24 17:38:59 2020

LFSR LFSR_inst
(
	.i_clk(i_clk_sig) ,	// input  i_clk_sig
	.i_rst_n(i_rst_n_sig) ,	// input  i_rst_n_sig
	.timer(timer_sig) ,	// input [7:0] timer_sig
	.data_out(data_out_sig) 	// output [3:0] data_out_sig
);

